### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by cucrui** [Burton2000/CS231n-2017#2]
hey, bro, I have a question in k_nearest_neighbor.py line 139. why X_squared need to add newaxis while Y_squared doesnt

**Comment by Burton2000** [comment]
The quick answer is so the variables can broadcast correctly so we can actually add them together. If you were to also add a new axis to **Y_squared** you then have 2 numpy arrays with different shapes that numpy can not add together.

---

The longer answer is:
**X_squared** has shape: (num_test, )
**Y_squared** has shape: (num_train, )
**XY** has shape: (num_test, num_train)

We add a new axis to **X_squared**
**X_squared** now has shape (num_test, 1)

Numpy will now let you add **X_squared** to **Y_squared** because of its broadcasting rules. 

You can think of what happens during broadcasting as 'stretching' **X_squared** along the axis we just added to make it num_train in length. Numpy will then apply the add operation across all the rows (i.e. **Y_squared** will be added to each row of the 'stretched' **X_squared** ). 

Instead of adding a new axis to **X_squared** we could have added a new axis to **Y_squared** and broadcasting would have allowed this. But, the shape coming out would be (num_train, num_test) which would not add to **XY** which has shape (num_test, num_train). Because of this we know we must add the new axis to **X_squared**. 

Let me know if that explains it to you, for more info look here: 
https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
https://medium.com/dataholiks-distillery/l2-distance-matrix-vectorization-trick-26aa3247ac6c
https://stackoverflow.com/questions/31587802/numpy-add-a-vector-to-matrix-column-wise

**Comment by cucrui** [comment]
really useful,thanks bro!
